name: Static analysis

on:
  [push, pull_request] # Pull request trigger should run the tests on merged files
   
# Not currently using a build type
# env:
#   # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
#   BUILD_TYPE: Release

jobs:
  sa:
    # This script uses linux specific commands, so is unlikely to work on a windows runner.
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - uses: daft-engineers/vocoder@v1

    - name: Analyse
      run: ${{github.workspace}}/checks.sh --static-analysis

